version: '3.9'

services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-data:/var/opt/mssql
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P $$SA_PASSWORD -Q 'SELECT 1'" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build:
      context: ./backend/movies-rest-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
    networks:
      - app-network
      - frontend-backend-network

  frontend:
    build:
      context: ./frontend/movies-frontend
    ports:
      - "${FRONTEND_PORT}:80"
    networks:
      - frontend-backend-network

networks:
  app-network:
    driver: bridge
  frontend-backend-network:
    driver: bridge

volumes:
  mssql-data:
